spring.application.name=geoshield-backend

spring.data.mongodb.uri=mongodb://localhost:27017/geoshield_db


server.port=8080

jwt.secret=geoshield-super-secure-jwt-secret-key-2025!!
jwt.expiration=3600000